### ISSUE TITLE
Analisando o código da amiguinha

### ISSUE THREAD

**Issue by CapistranoIFCE** [Thaynara-Andrade/SEMANA-SAUDAVEL#2]
+ Amiga, seria bacana que caso eu entrasse em outro números no MENU OPÇÕES, não quebrasse e sim surgisse uma pergunta, para eu entrar com o número correto.

https://github.com/Thaynara-Andrade/SEMANA-SAUDAVEL/blob/5369d0a7e1e6bf55fe19336a95c6bdc0eb631f8a/main.swift#L60

Fora isso, teu programa está muito bacana. Parabéns miga!

**Comment by Thaynara-Andrade** [comment]
Obrigado amigo, você me ajudou muito! 🥰
