### ISSUE TITLE
Importância de Nomes

### ISSUE THREAD

**Issue by MoysesAz** [Thaynara-Andrade/SEMANA-SAUDAVEL#3]
Primeiramente, queria parabenizar o seu trabalho e esforço.

Nomes têm que ser muito bem pensados e repensados. Desde o nome dos módulos ( [class.swift](https://github.com/Thaynara-Andrade/SEMANA-SAUDAVEL/blob/main/class.swift), [func.swift](https://github.com/Thaynara-Andrade/SEMANA-SAUDAVEL/blob/main/func.swift) ),  de variáveis e principalmente de funções (class menuPer, getInt). 

Alguns links que podem ajudar:
https://medium.com/lets-grow/clean-code-1-a-import%C3%A2ncia-dos-nomes-1203b2f3300b
https://www.youtube.com/watch?v=kw3H7nj9kc4

**Comment by Thaynara-Andrade** [comment]
Obrigada!!
