### ISSUE TITLE
Sobre os commits

### ISSUE THREAD

**Issue by mill3na** [Thaynara-Andrade/SEMANA-SAUDAVEL#4]
https://github.com/Thaynara-Andrade/SEMANA-SAUDAVEL/blob/ae1e9749ce4382b0eaa16f8412db46ed146ec171/class.swift#L26-L28

Oi, Thaynara! Parabéns pela sua aplicação! 
Queria te sugerir que envie para o github as atualizações que realmente fazem sentido para o controle de versão do seu código. Essa função, por exemplo, está vazia. Seria interessante enviar as mudanças que já foram previamente testadas e cumprem sua função. :) 
Manter o código limpo também é muito importante (que é a sugestão do Moysés).

Qualquer dúvida, estou à disposição ! :)

**Comment by Thaynara-Andrade** [comment]
Obrigada!
